#!/bin/sh

PREFIX=$1
VCFDIR=$2
VCF=$3
MINMAF=$4

## example:
## PREFIX=SCZ4000
## VCFDIR=SCZ
## VCF=CHR6
## MINMAF=15

GRAPH=${PREFIX}_${VCF}_${MINMAF}
VCFFILE=$VCFDIR/$VCF.vcf.gz
TRAINLABELS=$PREFIX.train.labels.txt
TESTLABELS=$PREFIX.test.labels.txt

## build the graph and train paths
echo "##########"
echo "########## BUILDING $GRAPH"
echo "##########"
./run-graph-vcf $GRAPH $TRAINLABELS $VCFFILE $MINMAF
mv $GRAPH.paths.txt.$TRAINLABELS $GRAPH.train.paths.txt

## build the test paths on the same graph
echo "##########"
echo "########## BUILDING $GRAPH TEST AND COMBINED PATHS"
echo "##########"
./run-graph-vcf-paths $GRAPH $TESTLABELS $VCFFILE
mv $GRAPH.paths.txt.$TESTLABELS $GRAPH.test.paths.txt
cat $GRAPH.train.paths.txt $GRAPH.test.paths.txt > $GRAPH.both.paths.txt

