#!/bin/sh

GRAPH=$1

./run-graphutils-arff $1 $1.testing.paths.txt
mv $GRAPH.arff $GRAPH.testing.arff

./run-graphutils-arff $1 $1.paths.txt

echo "########## Weka Decision Stump ##########"
./run-wekads $GRAPH

echo "########## Weka Random Forest ##########"
./run-wekarf $GRAPH 100 0
