#!/bin/sh

GRAPH=$1
TRAINPATHFILE=$2
TESTPATHFILE=$3

echo "##########"
echo "########## CLASSIFYING $GRAPH WITH WEKA"
echo "##########"

./run-graphutils-arff $GRAPH $TRAINPATHFILE
mv $GRAPH.arff $GRAPH.train.arff

./run-graphutils-arff $GRAPH $TESTPATHFILE
mv $GRAPH.arff $GRAPH.test.arff

./run-wekads $GRAPH

./run-wekarf $GRAPH 100 0
