#!/bin/sh

FRPREFIX=$1
PARAMNUMBER=$2

## remove old files
rm $FRPREFIX-combined*

## combine the runs
cat $FRPREFIX-*.frs.txt > $FRPREFIX-combined.frs.txt
cp $FRPREFIX-$PARAMNUMBER.params.txt $FRPREFIX-combined.params.txt

## form the combined-best file
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -extractbest -f $FRPREFIX-combined > $FRPREFIX-combined-best.frs.txt
cp $FRPREFIX-combined.params.txt $FRPREFIX-combined-best.params.txt

