#!/bin/sh
# usage: FRUtils
#  -arff,--arff                     print out an ARFF style file from the
#                                   data given by inputprefix
#  -f,--frsprefix <arg>             prefix of FRs file (e.g. HLAA-0.0-Inf)
#  -g,--graphprefix <arg>           prefix of graph file (e.g. HLAA)
#  -m,--minsupport <arg>            minimum number (not fraction) of
#                                   supporting paths for an FR to be
#                                   considered interesting
#  -mp,--maxpvalue <arg>            maximum p-value for an FR to be
#                                   considered interesting
#  -mpri,--minpriority <arg>        minimum priority value for an FR to be
#                                   considered interesting
#  -p,--pathsprefix <arg>           prefix of paths file (e.g. HLAA)

GRAPH=$1
FRPREFIX=$2

MINSUPPORT=$3
MAXP=$4
MINPRI=$5

## make the filtered SVM files
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -arff -g $GRAPH -p $GRAPH         -f $FRPREFIX \
	--minsupport $MINSUPPORT --maxpvalue $MAXP --minpriority $MINPRI
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -arff -g $GRAPH -p $GRAPH.test -f $FRPREFIX \
	--minsupport $MINSUPPORT --maxpvalue $MAXP --minpriority $MINPRI

## remove the extra chunk from the file names
mv $FRPREFIX.$GRAPH.arff $FRPREFIX.arff
mv $FRPREFIX.$GRAPH.test.arff $FRPREFIX.test.arff

## SMO cross-validation grid search options
TRAINFILE=$FRPREFIX.train.arff
TESTFILE=$FRPREFIX.test.arff

KFOLD=10
NGRIDSEARCH=0
CPOWERSTEP=1
GAMMAPOWERSTEP=1
GAMMAPOWERBEGIN=-30
GAMMAPOWEREND=-10


## run grid search in several batches because can't get more than about 10 threads per job
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 5 -ce 5 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 6 -ce 6 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 7 -ce 7 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 8 -ce 8 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 9 -ce 9 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 10 -ce 10 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 11 -ce 11 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &
