#!/bin/sh

PREFIX=$1

RANGEFILE="$PREFIX.svm.range.txt"

SVMFILE="$PREFIX.testing.svm.txt"
SCALEFILE="$PREFIX.testing.svm.scale.txt"

echo "Scaling $SVMFILE to $SCALEFILE from $RANGEFILE"
java -server -cp "build/install/fr/lib/*" org.ncgr.svm.SvmScaler -r $RANGEFILE -d $SVMFILE > $SCALEFILE
