#!/bin/sh
# usage: Predictor [options]
# -b,--predict-probability   toggle prediction of probability estimates
#                            [false]
# -datafile <arg>            input data file in SVM format [required]
# -modelfile <arg>           output model file [required]
# -outputfile <arg>          output prediction file [required]
# -v,--verbose               verbose output

PREFIX=$1

MODELFILE="$PREFIX.svm.model.txt"

DATAFILE="$PREFIX.testing.svm.scale.txt"
OUTPUTFILE="$PREFIX.testing.svm.pred.txt"

## run the SVM predictor
echo "Running Predictor on $DATAFILE and $MODELFILE with output to $OUTPUTFILE"
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.libsvm.Predictor -v -datafile $DATAFILE -modelfile $MODELFILE -outputfile $OUTPUTFILE

