#!/bin/bash
# usage: WekaRandomForest
#  -a,--arfffile <arg>         input data file in ARFF format (required)
#  -cv,--crossvalidate         run cross-validation
#  -gs,--gridsearch            run a grid search over parameters
#  -I,--iterations <arg>       some parameter to be decided
#  -k,--kfold <arg>            cross-validation k-fold (required)
#  -L,--tolerance <arg>        tolerance parameter [1.0e-3]
#  -M,--fitcalibrationmodels   fit calibration models to SVM outputs
#  -N,--normalization <arg>    0=normalize, 1=standardize, 2=neither [0]
#  -ng,--ngridsearch <arg>     set number of cases+controls (equal) to use
#                              in grid search [0=all]
#  -P,--epsilon <arg>          epsilon for round-off error [1.0e-12]
#  -test,--test                run training/testing on datasets
#  -tf,--testfile <arg>        test data file in ARFF format

PREFIX=$1
ITERATIONS=$2

TRAINFILE=$PREFIX.arff
TESTFILE=$PREFIX.testing.arff

echo "Running WekaRandomForest training on $TRAINFILE and testing on $TESTFILE with $ITERATIONS iterations"
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaRandomForest --test --arfffile=$TRAINFILE --testfile=$TESTFILE --iterations=$ITERATIONS

