#!/bin/bash
# usage: GridSearcher [options]
#  -Cstep <arg>       step for n in C=2^n [1]
#  -datafile <arg>    input data file in SVM format [required]
#  -gammastep <arg>   step for n in gamma=2^n [1]
#  -k <arg>           k-fold for cross validation [10]
#  -kernel <arg>      choose the SVM kernel: LINEAR, POLY, RBF, SIGMOID,
#                     PRECOMPUTED [RBF]
#  -ncases <arg>      set number of cases to use in search [0=all]
#  -ncontrols <arg>   set number of controls to use in search [0=all]
#  -v                 toggle verbose output

KERNEL=$1
PREFIX=$2

SVMFILE="$PREFIX.svm.txt"
RANGEFILE="$PREFIX.svm.range.txt"
SCALEFILE="$PREFIX.svm.scale.txt"
GRIDFILE="$PREFIX.svm.grid.txt"

## grid scan parameters
K=10
NGRIDCASES=200
NGRIDCONTROLS=200
C_POWER_STEP=1
GAMMA_POWER_STEP=1

ARGS="-datafile $SCALEFILE -k $K -ncases $NGRIDCASES -ncontrols $NGRIDCONTROLS -Cstep $C_POWER_STEP -gammastep $GAMMA_POWER_STEP -kernel $KERNEL"

## scale the SVM data if necessary
if [ ! -s $SCALEFILE ]
then
    echo "Scaling $SVMFILE"
    java -server -cp "build/install/pangenomics/lib/*" org.ncgr.libsvm.Scaler -s $RANGEFILE -d $SVMFILE > $SCALEFILE
fi

echo "Running GridSearcher with $ARGS"
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.libsvm.GridSearcher -v $ARGS > $GRIDFILE
