#!/bin/bash
# usage: WekaRandomForest
#  -a,--arfffile <arg>         ARFF input file (required)
#  -S,--seed <arg>             seed of randomization (1)

INPUTPREFIX=$1

## ARFF filtering parameters
ARFFFILE=$INPUTPREFIX.arff
NUMCASEPATHS=0
NUMCTRLPATHS=0
MINSIZE=0
MINSUPPORT=0
MAXPVALUE=1.0
PRIORITYOPTION=3
MINPRIORITY=1

KFOLD=10

if [ ! -s $ARFFFILE ]
then
    echo "Writing $ARFFFILE with $NUMCASEPATHS cases and $NUMCTRLPATHS controls"
    java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -arff \
	    -i $INPUTPREFIX -ncase $NUMCASEPATHS -nctrl $NUMCTRLPATHS -s $MINSIZE -m $MINSUPPORT -mp $MAXPVALUE -pri $PRIORITYOPTION -mpri $MINPRIORITY
fi
    
java -server -cp "build/install/fr/lib/*" org.ncgr.weka.WekaRandomTree -a $ARFFFILE -k $KFOLD
