#!/bin/sh
# usage: GraphUtils
#  -arff,--printarfffile             print out an ARFF file of path node
#                                    participation
#  -g,--graph <arg>                  name of graph
#  -maxmgf,--maxmgf <arg>            maximum MGF of loci to be included from
#                                    a VCF/List file [1.0]
#  -minmgf,--minmgf <arg>            minimum MGF of loci to be included from
#                                    a VCF/List file [0.01]
#  -nodepaths,--printnodepathsfile   print out node paths file
#  -nodes,--nodesfile <arg>          load graph nodes from this nodes.txt
#                                    file
#  -paths,--pathsfile <arg>          load graph paths from this paths.txt
#                                    file
#  -pca,--printpcafile               print out path pca file
#  -prs,--computeprs                 compute polygenic risk scores
#  -svm,--printsvmfile               print out a LIBSVM-compatible file of
#                                    path node participation

GRAPH=$1
PATHSFILE=$2

NODESFILE=$GRAPH.nodes.txt

echo "Building ARFF file from $NODESFILE and $PATHSFILE"
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.GraphUtils -arff --graph=$GRAPH --nodesfile=$NODESFILE --pathsfile=$PATHSFILE

