#!/bin/bash
# usage: GridSearcher [options]
#  -cb,--cpowerbegin <arg>        begining 2^n exponent in C scan [-5]
#  -ce,--cpowerend <arg>          ending 2^n exponent in C scan [15]
#  -cs,--cpowerstep <arg>         step for 2^n exponent in C scan [1]
#  -d,--datafile <arg>            input data file in SVM format [required]
#  -gb,--gammapowerbegin <arg>    begining 2^n exponent in RBF gamma scan
#                                 [-25]
#  -ge,--gammapowerend <arg>      ending 2^n exponent in RBF gamma scan [0]
#  -gs,--gammapowerstep <arg>     step for 2^n exponent in RBF gamma scan
#                                 [1]
#  -k,--kernel <arg>              choose the SVM kernel: LINEAR, POLY, RBF,
#                                 SIGMOID, PRECOMPUTED [RBF]
#  -ncases,--ncases <arg>         set number of cases to use in search
#                                 [0=all]
#  -ncontrols,--ncontrols <arg>   set number of controls to use in search
#                                 [0=all]
#  -nr,--nr <arg>                 nr-fold for cross validation [10]
#  -v,--verbose                   toggle verbose output

PREFIX=$1
KERNEL=$2

RANGEFILE="$PREFIX.svm.range.txt"
SCALEFILE="$PREFIX.svm.scale.txt"
GRIDFILE="$PREFIX.svm.grid.txt"

## grid scan parameters
NRFOLD=10
NCASES=200
NCONTROLS=200
NCASES=0
NCONTROLS=0

CPOWERBEGIN=5
CPOWEREND=11
CPOWERSTEP=1
GAMMAPOWERBEGIN=-30
GAMMAPOWEREND=-10
GAMMAPOWERSTEP=1

ARGS="-d $SCALEFILE -nr $NRFOLD -ncases $NCASES -ncontrols $NCONTROLS -k $KERNEL -cb $CPOWERBEGIN -ce $CPOWEREND -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP"

echo "Running GridSearcher with $ARGS"
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.libsvm.GridSearcher -v $ARGS > $GRIDFILE
