#!/bin/sh
# usage: FrequentedRegion
#  -a,--alpha <arg>                starting value of alpha for a scan (can
#                                  equal alphaend)
#  -ep,--excludedpathnodes <arg>   exclude paths that include any of the
#                                  given nodes []
#  -gfa,--gfa                      load from [graph].paths.gfa
#  -graph,--graph <arg>            graph name
#  -ip,--includedpathnodes <arg>   include only paths that include at least
#                                  one of the given nodes []
#  -k,--kappa <arg>                starting value of kappa for a scan (can
#                                  equal kappaend)
#  -n,--nodes <arg>                set of nodes to calculate FR e.g.
#                                  [1,2,3,4,5]
#  -p,--pathsfile <arg>            paths.txt file
#  -pri,--priorityoption <arg>     option for priority weighting of FRs:
#                                  0:label=total support or label support
#                                  [null,case,ctrl], 1:label=(label
#                                  support-other support) [case,ctrl,alt],
#                                  2=|case support-control support|,
#                                  3:label=O.R. in label's favor
#                                  [null,case,ctrl], 4=Fisher's exact test
#                                  two-tailed p value
#  -txt,--txt                      load from [graph].nodes.txt and
#                                  [graph].paths.txt

graph=$1
pathsfile=$2
alpha=$3
kappa=$4
priorityoption=$5
nodes=$6

## priorityoption doesn't matter, we're just looking at an FR with alpha, kappa
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FrequentedRegion \
     --txt --graph=$graph --pathsfile=$pathsfile --alpha=$alpha --kappa=$kappa --priorityoption=$priorityoption --nodes=$nodes $7 $8 $9
