#!/bin/sh
# usage: GraphUtils
#  -arff,--printarfffile             print out an ARFF file of path node
#                                    participation
#  -g,--graph <arg>                  name of graph
#  -list,--listfile <arg>            load sample(s) from a PLINK list file
#  -maxmaf,--maxmaf <arg>            maximum MAF of loci to be included from
#                                    LIST or VCF file [1.0]
#  -mgf,--mgf <arg>                  minimum MGF for inclusion
#  -minmaf,--minmaf <arg>            minimum MAF of loci to be included from
#                                    LIST or VCF file [0.0]
#  -nodepaths,--printnodepathsfile   print out node paths file
#  -pca,--printpcafile               print out path pca file
#  -prs,--prs                        compute polygenic risk scores
#  -samplefile <arg>                 file containing samples+labels to
#                                    determine paths through the given graph
#                                    (-g) from a VCF (-vcf) or LIST (-list)
#  -svm,--printsvmfile               print out a LIBSVM-compatible file of
#                                    path node participation
#  -vcf,--vcffile <arg>              load sample(s) from a VCF file

GRAPHPREFIX=$1
LISTFILE=$2
LABELSPREFIX=$3
MINMAF=$4

## compute paths from a PLINK list file
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.GraphUtils \
	-g $GRAPHPREFIX -list $LISTFILE -samplefile $LABELSPREFIX.labels.txt > $GRAPHPREFIX.$LABELSPREFIX.paths.txt

