#!/bin/bash

INPUTPREFIX=$1
ARFFFILE=$INPUTPREFIX.arff

## HLAA has 4966/6243
NUMCASEPATHS=0
NUMCTRLPATHS=0

MINSIZE=0
MINSUPPORT=0
MAXPVALUE=1.0

## delete former ARFF file
rm -f $ARFFFILE

if [ ! -s $ARFFFILE ]
then
    echo "Writing $ARFFFILE with $NUMCASEPATHS cases and $NUMCTRLPATHS controls"
    java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -arff -i $INPUTPREFIX -ncase $NUMCASEPATHS -nctrl $NUMCTRLPATHS -s $MINSIZE -m $MINSUPPORT -mp $MAXPVALUE
fi
    
if [ -s $ARFFFILE ]
then
    java -server -cp "build/install/fr/lib/*" WekaTest $ARFFFILE
fi
