#!/bin/bash
# usage: FRUtils
#  -arff,--arff                     print out an ARFF style file from the
#                                   data given by inputprefix
#  -i,--inputprefix <arg>           prefix of input files (e.g.
#                                   HLAA-0.1-Inf)
#  -m,--minsupport <arg>            minimum number of supporting paths for
#                                   an FR to be considered interesting
#  -mp,--maxpvalue <arg>            maximum p-value for an FR to be
#                                   considered interesting
#  -mpri,--minpriority <arg>        minimum priority value for an FR to be
#                                   considered interesting
#  -ncase,--numcasepaths <arg>      number of case paths to include in SVM
#                                   or ARFF or TXT output
#  -nctrl,--numcontrolpaths <arg>   number of control paths to include in
#                                   SVM or ARFF or TXT output
#  -p,--postprocess                 postprocess by applying new minsup,
#                                   minsize to an FR set given by
#                                   inputprefix
#  -pathfrs,--pathfrs               print out a pathfrs.txt style file from
#                                   the FR data given by inputprefix
#  -s,--minsize <arg>               minimum number of nodes that a FR must
#                                   contain to be considered interesting
#  -svm,--svm                       print out an SVM style file from the
#                                   data given by inputprefix

INPUTPREFIX=$1

## PATHFRS options
NUMCASEPATHS=0
NUMCTRLPATHS=0
MINSUPPORT=1000
MINPRIORITY=250

echo "Writing $INPUTPREFIX.pathfrs.txt with $NUMCASEPATHS cases and $NUMCTRLPATHS controls"
java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -pathfrs -i $INPUTPREFIX -ncase $NUMCASEPATHS -nctrl $NUMCTRLPATHS -m $MINSUPPORT -mpri $MINPRIORITY $2 $3 $4 $5 $6 $7 $8 $9
