#!/bin/sh
# usage: PangenomicGraph
#  -ecc,--equalizecasescontrols   reduce cases or controls to make equal in
#                                 number [false]
#  -g,--graph <arg>               name of graph (required)
#  -l,--labelsfile <arg>          tab-delimited file containing one
#                                 sample<tab>label pair per line for desired
#                                 paths
#  -list,--listfile <arg>         build graph nodes/paths from a PLINK list
#                                 file
#  -maxc,--maxcases <arg>         maxiumum number of case paths in the graph
#                                 [no limit]
#  -maxmaf,--maxmaf <arg>         maximum MAF/MGF of loci to be included on
#                                 graph [1.00]
#  -minmaf,--minmaf <arg>         minimum MAF/MGF of loci to be included on
#                                 graph [0.01]
#  -n,--buildnodes                build graph nodes (this or --paths
#                                 required)
#  -nodes,--nodesfile <arg>       read graph nodes from a nodes.txt file
#  -p,--buildpaths                build graph paths (this or --nodes
#                                 required)
#  -paths,--pathsfile <arg>       read graph paths from a paths.txt file
#  -v,--verbose                   verbose output (false)
#  -vcf,--vcffile <arg>           build graph nodes/paths from a
#                                 tabix-indexed gzipped VCF file

GRAPH=$1
LABELSFILE=$2
LISTFILE=$3

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.PangenomicGraph -v --buildpaths \
     --graph=$GRAPH --nodesfile=$GRAPH.nodes.txt --labelsfile $LABELSFILE --listfile=$LISTFILE

