#!/bin/bash
# usage: WekaSMO
#  -a,--arfffile <arg>         input data file in ARFF format (required)
#  -C,--complexity <arg>       SMO complexity constant C
#  -cv,--crossvalidate         run cross-validation
#  -gs,--gridsearch            run a grid search over parameters
#  -k,--kfold <arg>            cross-validation k-fold (required)
#  -kp,--kernelparam <arb>     kernel parameter RBF:gamma, Poly:exponent
#  -kernel,--kernel <arg>      kernel function: RBF or Poly (required)
#  -L,--tolerance <arg>        tolerance parameter [1.0e-3]
#  -M,--fitcalibrationmodels   fit calibration models to SVM outputs
#  -N,--normalization <arg>    0=normalize, 1=standardize, 2=neither [0]
#  -ng,--ngridsearch <arg>     set number of cases+controls (equal) to use
#                              in grid search [0=all]
#  -P,--epsilon <arg>          epsilon for round-off error [1.0e-12]
#  -test,--test                run training/testing on datasets with given
#                              SMO and kernel parameters
#  -tf,--testfile <arg>        test data file in ARFF format

PREFIX=$1
KERNEL=$2
C=$3
KERNELPARAM=$4

TRAINFILE=$PREFIX.arff
TESTFILE=$PREFIX.testing.arff

echo "Running WekaSMO training on $TRAINFILE and testing on $TESTFILE with C=$C and kernelparam=$KERNELPARAM"
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --test --kernel=$KERNEL --arfffile=$TRAINFILE --testfile=$TESTFILE --complexity=$C --kernelparam=$KERNELPARAM

