#!/bin/bash
# usage: WekaDecisionStump
#  -a,--arfffile <arg>    ARFF input file (required)
#  -ab,--adaboost         use AdaBoost on the classifier
#  -cv,--crossvalidate    run cross-validation
#  -D,--debug             toggle on debug mode [false]
#  -k,--kfold <arg>       cross-validation k-fold [10]
#  -test,--test           run training/testing on datasets
#  -tf,--testfile <arg>   test data file in ARFF format

PREFIX=$1

TRAINFILE=$PREFIX.arff
TESTFILE=$PREFIX.testing.arff

KFOLD=10

#echo "WekaDecisionStump $KFOLD-fold cross-validation on $TRAINFILE"
#java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaDecisionStump --crossvalidate --arfffile=$TRAINFILE --kfold=$KFOLD $2

echo "WekaDecisionStump training/testing on $TRAINFILE and $TESTFILE"
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaDecisionStump --test --arfffile=$TRAINFILE --testfile=$TESTFILE $2

