#!/bin/sh

GRAPH=$1
FRPREFIX=$2

MINSUPPORT=$3
MAXP=$4
MINPRI=$5

## make the filtered SVM files
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -svm -g $GRAPH -p $GRAPH         -f $FRPREFIX \
	--minsupport $MINSUPPORT --maxpvalue $MAXP --minpriority $MINPRI
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -svm -g $GRAPH -p $GRAPH.testing -f $FRPREFIX \
	--minsupport $MINSUPPORT --maxpvalue $MAXP --minpriority $MINPRI

## remove the extra chunk from the file names
mv $FRPREFIX.$GRAPH.svm.txt $FRPREFIX.svm.txt
mv $FRPREFIX.$GRAPH.testing.svm.txt $FRPREFIX.testing.svm.txt

## scale the SVM files
./run-libsvmscaler-samples $FRPREFIX
./run-libsvmscaler-testing $FRPREFIX

## run GridSearch with RBF
./run-libsvmgridsearch $FRPREFIX RBF
