#!/bin/sh
# usage: PangenomicGraph
#  -ecc,--equalizecasescontrols   reduce cases or controls to make equal in
#                                 number [false]
#  -g,--graph <arg>               name of graph (required)
#  -l,--labelsfile <arg>          tab-delimited file containing one
#                                 sample<tab>label pair per line for desired
#                                 paths
#  -list,--listfile <arg>         build graph nodes/paths from a PLINK list
#                                 file
#  -maxc,--maxcases <arg>         maxiumum number of case paths in the graph
#                                 [no limit]
#  -maxmaf,--maxmaf <arg>         maximum MAF/MGF of loci to be included on
#                                 graph [1.00]
#  -minmaf,--minmaf <arg>         minimum MAF/MGF of loci to be included on
#                                 graph [0.01]
#  -n,--buildnodes                build graph nodes (this or --paths
#                                 required)
#  -nodes,--nodesfile <arg>       read graph nodes from a nodes.txt file
#  -p,--buildpaths                build graph paths (this or --nodes
#                                 required)
#  -paths,--pathsfile <arg>       read graph paths from a paths.txt file
#  -v,--verbose                   verbose output (false)
#  -vcf,--vcffile <arg>           build graph nodes/paths from a
#                                 tabix-indexed gzipped VCF file

## Graves	pheno_241.2
## IBD		pheno_555
## lupus	pheno_695.42
## rheum	pheno_714.1
## T1D		pheno_250.1

LISTFILE=HLA_PHEWAS.list

DISEASE=HLA_PHEWAS_${1}

NODESFILE=${DISEASE}_${2}.nodes.txt

LABELSFILE=$DISEASE.testing.labels.txt

GRAPH=${DISEASE}_${2}.testing

## run all cases/controls in labels file
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.PangenomicGraph -v  --buildpaths \
     --graph=$GRAPH --nodesfile=$NODESFILE --listfile=$LISTFILE  --labelsfile=$LABELSFILE
