#!/bin/sh
# usage: FRUtils
#  -arff,--arff                     print out an ARFF style file from the
#                                   data given by inputprefix
#  -f,--frsprefix <arg>             prefix of FRs file (e.g. HLAA-0.0-Inf)
#  -g,--graphprefix <arg>           prefix of graph file (e.g. HLAA)
#  -m,--minsupport <arg>            minimum number (not fraction) of
#                                   supporting paths for an FR to be
#                                   considered interesting
#  -mp,--maxpvalue <arg>            maximum p-value for an FR to be
#                                   considered interesting
#  -mpri,--minpriority <arg>        minimum priority value for an FR to be
#                                   considered interesting
#  -p,--pathsprefix <arg>           prefix of paths file (e.g. HLAA)

GRAPH=$1
FRPREFIX=$2

MINSUPPORT=0
MAXP=1
MINPRI=0

## make the filtered ARFF files
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -arff -g $GRAPH -p $GRAPH.train -f $FRPREFIX \
	--minsupport $MINSUPPORT --maxpvalue $MAXP --minpriority $MINPRI
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -arff -g $GRAPH -p $GRAPH.test  -f $FRPREFIX \
	--minsupport $MINSUPPORT --maxpvalue $MAXP --minpriority $MINPRI

## remove the extra chunk from the file names
mv $FRPREFIX.$GRAPH.train.arff $FRPREFIX.train.arff
mv $FRPREFIX.$GRAPH.test.arff $FRPREFIX.test.arff

## run Weka DecisionStump
./run-wekads $FRPREFIX

## run Weka RandomForest
./run-wekarf $FRPREFIX 100 0
