#!/bin/sh
# usage: FRUtils
#  -arff,--arff                     print out an ARFF style file from the
#                                   data given by inputprefix
#  -f,--frsprefix <arg>             prefix of FRs file (e.g. HLAA-0.0-Inf)
#  -g,--graphprefix <arg>           prefix of graph file (e.g. HLAA)
#  -m,--minsupport <arg>            minimum number (not fraction) of
#                                   supporting paths for an FR to be
#                                   considered interesting
#  -mp,--maxpvalue <arg>            maximum p-value for an FR to be
#                                   considered interesting
#  -mpri,--minpriority <arg>        minimum priority value for an FR to be
#                                   considered interesting
#  -p,--pathsprefix <arg>           prefix of paths file (e.g. HLAA)

GRAPH=$1
FRPREFIX=$2

MINSUPPORT=$3
MAXP=$4
MINPRI=$5

## make the filtered SVM files
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -arff -g $GRAPH -p $GRAPH         -f $FRPREFIX \
	--minsupport $MINSUPPORT --maxpvalue $MAXP --minpriority $MINPRI
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -arff -g $GRAPH -p $GRAPH.testing -f $FRPREFIX \
	--minsupport $MINSUPPORT --maxpvalue $MAXP --minpriority $MINPRI

## remove the extra chunk from the file names
mv $FRPREFIX.$GRAPH.arff $FRPREFIX.arff
mv $FRPREFIX.$GRAPH.testing.arff $FRPREFIX.testing.arff

./run-wekads $FRPREFIX $6
