#!/bin/bash
# usage: FRUtils
#  -arff,--arff                     print out an ARFF style file from the
#                                   data given by inputprefix
#  -i,--inputprefix <arg>           prefix of input files (e.g.
#                                   HLAA-0.1-Inf)
#  -m,--minsupport <arg>            minimum number of supporting paths for
#                                   an FR to be considered interesting
#  -mp,--maxpvalue <arg>            maximum p-value for an FR to be
#                                   considered interesting
#  -mpri,--minpriority <arg>        minimum priority value for an FR to be
#                                   considered interesting
#  -ncase,--numcasepaths <arg>      number of case paths to include in SVM
#                                   or ARFF output
#  -nctrl,--numcontrolpaths <arg>   number of control paths to include in
#                                   SVM or ARFF output
#  -p,--postprocess                 postprocess by applying new minsup,
#                                   minsize to an FR set given by
#                                   inputprefix
#  -s,--minsize <arg>               minimum number of nodes that a FR must
#                                   contain to be considered interesting
#  -svm,--svm                       print out an SVM style file from the
#                                   data given by inputprefix

INPUTPREFIX=$1

## ARFF options
ARFFFILE=$INPUTPREFIX.arff
NUMCASEPATHS=0
NUMCTRLPATHS=0
MINSUPPORT=500
MINPRIORITY=1

## WEKA options
NRUNS=10

## delete former ARFF file
#rm -f $ARFFFILE

if [ ! -s $ARFFFILE ]
then
    echo "Writing $ARFFFILE with $NUMCASEPATHS cases and $NUMCTRLPATHS controls"
    java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -arff -i $INPUTPREFIX -ncase $NUMCASEPATHS -nctrl $NUMCTRLPATHS -m $MINSUPPORT -mpri $MINPRIORITY $2 $3 $4 $5 $6 $7 $8 $9
fi

# usage: WekaTest [options]
#  -i,--inputfile <arg>   input file containing feature vectors in ARFF
#                         format
#  -nruns <arg>           number of parallel runs [1]

if [ -s $ARFFFILE ]
then
    java -server -Xms10g -Xmx500g -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -cp "build/install/fr/lib/*" org.ncgr.weka.WekaTest -i $ARFFFILE -nruns $NRUNS
fi

echo $ARFFFILE
