#!/bin/sh
# usage: GraphUtils
#  -g,--graph <arg>         name of graph
#  -list,--listfile <arg>   load sample(s) from a PLINK list file
#  -mgf,--mgf <arg>         minimum MGF for inclusion
#  -prs,--prs               compute polygenic risk scores
#  -samplepath <arg>        determine the path through the given graph for
#                           the given sample name from a VCF (-vcf) or LIST
#                           (-list)
#  -vcf,--vcffile <arg>     load sample(s) from a VCF file

GRAPHPREFIX=$1
LISTPREFIX=$2
LABELSPREFIX=$3

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.GraphUtils -g $GRAPHPREFIX -list $LISTPREFIX.list -samplefile $LABELSPREFIX.labels.txt > $LABELSPREFIX.paths.txt
