#!/bin/bash
# usage: WekaSMO
#  -a,--arfffile <arg>         ARFF input file (required)
#  -C,--complexity <arg>       SMO complexity constant C
#  -cv,--crossvalidate         run cross-validation
#  -g,--gamma <arg>            RBF kernel gamma parameter
#  -gs,--gridsearch            run a grid search over parameters
#  -k,--kfold <arg>            cross-validation k-fold (required)
#  -L,--tolerance <arg>        tolerance parameter [1.0e-3]
#  -M,--fitcalibrationmodels   fit calibration models to SVM outputs
#  -N,--normalization <arg>    0=normalize, 1=standardize, 2=neither [0]
#  -ng,--ngridsearch <arg>     set number of cases+controls (equal) to use
#                              in grid search [0=all]
#  -P,--epsilon <arg>          epsilon for round-off error [1.0e-12]

PREFIX=$1
NGRIDSEARCH=$2

ARFFFILE=$PREFIX.arff

## SMO cross-validation options
KFOLD=10
    
## cross-validate
if [ -s $ARFFFILE ]
then
    echo "Running WekaSMO grid search on $ARFFFILE"
    java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$ARFFFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH
fi
