#!/bin/bash
# usage: FRUtils
#  -arff,--arff                     print out an ARFF style file from the
#                                   data given by inputprefix
#  -extractbest,--extractbestfrs    extract the best (last) FRs from a file
#                                   containing many runs, each starting with
#                                   the heading line
#  -i,--inputprefix <arg>           prefix of input files (e.g.
#                                   HLAA-0.1-Inf)
#  -m,--minsupport <arg>            minimum number of supporting paths for
#                                   an FR to be considered interesting
#  -mp,--maxpvalue <arg>            maximum p-value for an FR to be
#                                   considered interesting
#  -mpri,--minpriority <arg>        minimum priority value for an FR to be
#                                   considered interesting
#  -ncase,--numcasepaths <arg>      number of case paths to include in SVM
#                                   or ARFF or TXT output
#  -nctrl,--numcontrolpaths <arg>   number of control paths to include in
#                                   SVM or ARFF or TXT output
#  -p,--postprocess                 postprocess by applying new minsup,
#                                   minsize to an FR set given by
#                                   inputprefix
#  -pathfrs,--pathfrs               print out a pathfrs.txt style file from
#                                   the FR data given by inputprefix
#  -pri,--priorityoption <arg>      option for priority weighting of FRs:
#                                   0:label=total support or label support
#                                   [null,case,ctrl], 1:label=(label
#                                   support-other support) [case,ctrl,alt],
#                                   2=|case support-control support|,
#                                   3:label=O.R. in label's favor
#                                   [null,case,ctrl], 4=Fisher's exact test
#                                   two-tailed p value
#  -prs,--prs                       generate polynomial risk scores from
#                                   FRFinder output
#  -s,--minsize <arg>               minimum number of nodes that a FR must
#                                   contain to be considered interesting
#  -svm,--svm                       print out an SVM style file from the
#                                   data given by inputprefix

INPUTPREFIX=$1

java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -prs -pri 3 -i $INPUTPREFIX
