#!/bin/sh
# usage: PangenomicGraph
#  -arff,--printarfffile             print out an ARFF file of path node
#                                    participation [false]
#  -dncp,--dropnocallpaths           drop no-call nodes and paths that
#                                    traverse them [false]
#  -ecc,--equalizecasescontrols      reduce cases or controls to make equal
#                                    in number [false]
#  -g,--graph <arg>                  name of graph
#  -l,--labelfile <arg>              tab-delimited file containing one
#                                    sample<tab>label per line
#  -list,--listfile <arg>            load graph from a PLINK list file
#  -maxc,--maxcases <arg>            maxiumum number of cases in the graph
#  -nodepaths,--printnodepathsfile   print out node paths file [false]
#  -pca,--printpcafile               print out path pca file [false]
#  -svm,--printsvmfile               print out a LIBSVM-compatible file of
#                                    path node participation [false]
#  -txt,--txtfile <arg>              root name of a pair of TXT files
#                                    containing nodes and paths (e.g. FOO
#                                    means FOO.nodes.txt and FOO.paths.txt)
#  -v,--verbose                      verbose output (false)
#  -vcf,--vcffile <arg>              load graph from <graph>.vcf.gz

GRAPH=$1

MAXCASES=0

echo "Building ARFF from $GRAPH with $MAXCASES cases and $MAXCASES controls"
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.PangenomicGraph -arff -v -g $GRAPH -txt $GRAPH -ecc -maxc $MAXCASES

