#!/bin/bash
# usage: WekaSMO
#  -a,--arfffile <arg>           input data file in ARFF format (required)
#  -cb,--cpowerbegin <arg>       begining 2^n exponent in C scan [5]
#  -ce,--cpowerend <arg>         ending 2^n exponent in C scan [11]
#  -cs,--cpowerstep <arg>        step for 2^n exponent in C scan [1]
#  -gb,--gammapowerbegin <arg>   begining 2^n exponent in RBF gamma scan
#                                [-30]
#  -ge,--gammapowerend <arg>     ending 2^n exponent in RBF gamma scan [-10]
#  -gs,--gammapowerstep <arg>    step for 2^n exponent in RBF gamma scan [1]
#  -k,--kfold <arg>              cross-validation k-fold (required)
#  -ng,--ngridsearch <arg>       set number of cases+controls (equal) to use
#                                in grid search [0=all]

PREFIX=$1

TRAINFILE=$PREFIX.train.arff

KFOLD=10
NGRIDSEARCH=0
CPOWERSTEP=1
GAMMAPOWERSTEP=1
GAMMAPOWERBEGIN=-30
GAMMAPOWEREND=-10

## run grid search in several batches because can't get more than about 10 threads per job
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 5 -ce 5 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 6 -ce 6 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 7 -ce 7 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 8 -ce 8 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 9 -ce 9 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 10 -ce 10 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --gridsearch --arfffile=$TRAINFILE --kfold=$KFOLD --ngridsearch=$NGRIDSEARCH \
     -cb 11 -ce 11 -cs $CPOWERSTEP -gb $GAMMAPOWERBEGIN -ge $GAMMAPOWEREND -gs $GAMMAPOWERSTEP &
