#!/bin/bash
# usage: WekaSMO
#  -a,--arfffile <arg>         ARFF input file (required)
#  -C,--complexity <arg>       SMO complexity constant C
#  -cv,--crossvalidate         run cross-validation
#  -g,--gamma <arg>            RBF kernel gamma parameter
#  -gs,--gridsearch            run a grid search over parameters
#  -k,--kfold <arg>            cross-validation k-fold (required)
#  -L,--tolerance <arg>        tolerance parameter [1.0e-3]
#  -M,--fitcalibrationmodels   fit calibration models to SVM outputs
#  -N,--normalization <arg>    0=normalize, 1=standardize, 2=neither [0]
#  -ng,--ngridsearch <arg>     set number of cases+controls (equal) to use
#                              in grid search [0=all]
#  -P,--epsilon <arg>          epsilon for round-off error [1.0e-12]
#  -tr,--train                 run training on a dataset with given SMO and
#                              kernel parameters
#  -v,--verbose                verbosity toggle (false)

PREFIX=$1
C=$2
gamma=$3

KFOLD=10

ARFFFILE=$PREFIX.arff

if [ -s $ARFFFILE ]
then
    echo "Running WekaSMO cross-validation on $ARFFFILE with kvold=$KFOLD C=$C gamma=$gamma"
    java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaSMO --crossvalidate --arfffile=$ARFFFILE --kfold=$KFOLD --complexity=$C --gamma=$gamma
fi
