#!/bin/sh
# usage: GraphUtils
#  -arff,--printarfffile             print out an ARFF file of path node
#                                    participation
#  -g,--graph <arg>                  name of graph
#  -maxmaf,--maxmaf <arg>            maximum MAF/MGF of loci to be included
#                                    from a VCF/List file [1.0]
#  -minmaf,--minmaf <arg>            minimum MAF/MGF of loci to be included
#                                    from a VCF/List file [0.0]
#  -nodepaths,--printnodepathsfile   print out node paths file
#  -nodes,--nodesfile <arg>          load graph nodes from this nodes.txt
#                                    file
#  -paths,--pathsfile <arg>          load graph paths from this paths.txt
#                                    file
#  -pca,--printpcafile               print out path pca file
#  -prs,--computeprs                 compute polygenic risk scores
#  -svm,--printsvmfile               print out a LIBSVM-compatible file of
#                                    path node participation

GRAPHPREFIX=$1
LISTFILE=$2
LABELSPREFIX=$3
MINMAF=$4

## compute paths from a PLINK list file
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.GraphUtils \
	-g $GRAPHPREFIX -minmaf $4 -list $LISTFILE -samplefile $LABELSPREFIX.labels.txt > $GRAPHPREFIX.$LABELSPREFIX.paths.txt

