#!/bin/sh
# usage: PangenomicGraph
#  -arff,--printarfffile             print out an ARFF file of path node
#                                    participation [false]
#  -dncp,--dropnocallpaths           drop no-call nodes and paths that
#                                    traverse them [false]
#  -ecc,--equalizecasescontrols      reduce cases or controls to make equal
#                                    in number [false]
#  -g,--graph <arg>                  name of graph
#  -l,--labelfile <arg>              tab-delimited file containing one
#                                    sample<tab>label per line
#  -list,--listfile <arg>            load graph from a PLINK list file
#  -nodepaths,--printnodepathsfile   print out node paths file [false]
#  -pca,--printpcafile               print out path pca file [false]
#  -svm,--printsvmfile               print out a LIBSVM-compatible file of
#                                    path node participation [false]
#  -txt,--txtfile <arg>              root name of a pair of TXT files
#                                    containing nodes and paths (e.g. FOO
#                                    means FOO.nodes.txt and FOO.paths.txt)
#  -v,--verbose                      verbose output (false)
#  -vcf,--vcffile <arg>              load graph from <graph>.vcf.gz

# HLA_PHEWAS/
# ├── HLA_PHEWAS.list
# └── HLA_PHEWAS_T1D.labels.txt
GRAPHDIR=HLA_PHEWAS
GRAPH=HLA_PHEWAS_T1D
LABELSFILE=HLA_PHEWAS_T1D.labels.txt
LISTFILE=HLA_PHEWAS.list

java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.PangenomicGraph \
     -v -pca -arff -svm -ecc -g $GRAPHDIR/$GRAPH -l $GRAPHDIR/$LABELSFILE -list $GRAPHDIR/$LISTFILE $4 $5 $6
