#!/bin/bash
# usage: WekaRandomForest
#  -a,--arfffile <arg>           input data file in ARFF format (required)
#  -bo,--boostoption <arg>       boost method: Ada or Logit (none)
#  -bsp,--bagsizepercent <arg>   the size of each bag, as a percentage of
#                                the training set size [100]
#  -btr,--breaktiesrandomly      break ties randomly
#  -cv,--crossvalidate           run k-fold cross-validation
#  -d,--debug                    turn on debugging mode
#  -k,--kfold <arg>              cross-validation k-fold [10]
#  -md,--maxdepth <arg>          maximum depth of the tree [0=unlimited]
#  -nf,--numfeatures <arg>       number of features to use in random
#                                selection [0=automatic]
#  -ni,--numiterations <arg>     the number of bagging iterations [100]
#  -no,--numoptimize <arg>       the number of training/testing runs to
#                                optimize the model [10]
#  -op,--optimize                optimize model by running noptimize
#                                training/testing runs and choosing best
#  -test,--test                  run training/testing on arfffile/testfile
#  -tf,--testfile <arg>          test data file in ARFF format

PREFIX=$1

TRAINFILE=$PREFIX.arff
TESTFILE=$PREFIX.testing.arff

## parameters
NUMITERATIONS=100
NUMFEATURES=0
NUMOPTIMIZE=25

echo "WekaRandomForest testing/training optimization on $TRAINFILE and $TESTFILE"
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.weka.WekaRandomForest --optimize --arfffile=$TRAINFILE --testfile=$TESTFILE \
     --numiterations=$NUMITERATIONS --numfeatures=$NUMFEATURES --numoptimize=$NUMOPTIMIZE $2 $3
