#!/bin/sh
# usage: PangenomicGraph
#  -arff,--printarfffile             print out an ARFF file of path node
#                                    participation [false]
#  -dncp,--dropnocallpaths           drop no-call nodes and paths that
#                                    traverse them [false]
#  -ecc,--equalizecasescontrols      reduce cases or controls to make equal
#                                    in number [false]
#  -g,--graph <arg>                  name of graph
#  -l,--labelfile <arg>              tab-delimited file containing one
#                                    sample<tab>label per line
#  -list,--listfile <arg>            load graph from a PLINK list file
#  -maxc,--maxcases <arg>            maxiumum number of cases in the graph
#  -nodepaths,--printnodepathsfile   print out node paths file [false]
#  -pca,--printpcafile               print out path pca file [false]
#  -svm,--printsvmfile               print out a LIBSVM-compatible file of
#                                    path node participation [false]
#  -txt,--txtfile <arg>              root name of a pair of TXT files
#                                    containing nodes and paths (e.g. FOO
#                                    means FOO.nodes.txt and FOO.paths.txt)
#  -v,--verbose                      verbose output (false)
#  -vcf,--vcffile <arg>              load graph from <graph>.vcf.gz

## Graves	pheno_241.2
## IBD		pheno_555
## lupus	pheno_695.42
## rheum	pheno_714.1
## T1D		pheno_250.1

GRAPHDIR=HLA_PHEWAS
LISTFILE=HLA_PHEWAS.list

GRAPH=HLA_PHEWAS_$1
LABELSFILE=$GRAPH.labels.txt

## run all cases/controls in labels file
java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.PangenomicGraph -list $GRAPHDIR/$LISTFILE \
     -v -ecc -pca -arff -svm -g $GRAPHDIR/$GRAPH -l $GRAPHDIR/$LABELSFILE $4 $5 $6
