#!/bin/bash

INPUTPREFIX=$1
SVMFILE="$INPUTPREFIX.svm.txt"

## SVM file building parameters
NUMCASEPATHS=0
NUMCTRLPATHS=0
MINSIZE=0
MINSUPPORT=100
MINPRIORITY=1

## write the SVM file
echo "Writing $SVMFILE with -ncase $NUMCASEPATHS -nctrl $NUMCTRLPATHS -s $MINSIZE -m $MINSUPPORT -minp $MINPRIORITY"
java -server -cp "build/install/fr/lib/*" org.ncgr.pangenomics.genotype.fr.FRUtils -svm \
     -i $INPUTPREFIX -ncase $NUMCASEPATHS -nctrl $NUMCTRLPATHS -s $MINSIZE -m $MINSUPPORT -pri 3 -minp $MINPRIORITY
