#!/bin/sh
# usage: Util [options]
#  -datafile <arg>   SVM scaled data file
#  -predfile <arg>   SVM prediction output file (one line)
#  -s,--stats        compute prediction stats from datafile and predfile
#  -t,--transpose    transpose input file into SVM format

PREFIX=$1

DATAFILE="$PREFIX.svm.scale.txt"
PREDFILE="$PREFIX.svm.pred.txt"

## run the SVM stats computer
echo "Running Util --stats on $DATAFILE and $PREDFILE"
java -server -cp "build/install/pangenomics/lib/*" org.ncgr.libsvm.Util --stats -datafile $DATAFILE -predfile $PREDFILE
