#!/bin/sh
# usage: FRFinder
#  -a,--alpha <arg>                value of alpha (required)
#  -do,--debug                     debug output [false]
#  -en,--excludednodes <arg>       require that interesting FRs NOT contain
#                                  the given nodes []
#  -ep,--excludedpathnodes <arg>   exclude paths that include any of the
#                                  given nodes []
#  -graph,--graphname <arg>        graph name
#  -in,--includednodes <arg>       require that interesting FRs contain at
#                                  least one of the given nodes []
#  -ip,--includedpathnodes <arg>   include only paths that include at least
#                                  one of the given nodes []
#  -k,--kappa <arg>                value of kappa; -1=infinity (required)
#  -keep,--keepoption <arg>        option for keeping FRs in finder loop:
#                                  subset[:N]|distance[:N] [keep all]
#  -m,--minsupport <arg>           minimum number of supporting paths for an
#                                  FR to be considered interesting [1]
#  -maxct,--maxclocktime <arg>     limit the computation to the given clock
#                                  time in minutes [0=unlimited]
#  -maxs,--maxsize <arg>           maximum number of nodes that a FR can
#                                  contain to be considered interesting
#                                  [unlimited]
#  -mp,--minpriority <arg>         minimum priority for an FR to be
#                                  considered interesting [0=disabled]
#  -mr,--maxround <arg>            maximum FR-finding round to run
#                                  [0=unlimited]
#  -nodes,--nodesfile <arg>        read graph nodes from a nodes.txt file
#  -paths,--pathsfile <arg>        read graph paths from a paths.txt file
#  -pri,--priorityoption <arg>     option for priority weighting of FRs:
#                                  0:label=total support or label support
#                                  [null,case,ctrl], 1:label=(label
#                                  support-other support) [case,ctrl,alt],
#                                  2=|case support-control support|,
#                                  3:label=O.R. in label's favor
#                                  [null,case,ctrl], 4=Fisher's exact test
#                                  two-tailed p value
#  -r,--resume                     resume from a previous run [false]
#  -rbns,--requirebestnodeset      require the best NodeSet from the
#                                  previous round in the next round [false]
#  -rn,--requirednodes <arg>       require that interesting FRs contain the
#                                  given nodes []
#  -rns,--requirednodescan <arg>   starting and ending node for a single
#                                  required node scan, e.g. 1-12345
#  -rsp,--requiresameposition      require that interesting FRs consist of
#                                  nodes at same genomic position [false]
#  -s,--minsize <arg>              minimum number of nodes that a FR must
#                                  contain to be considered interesting [1]
#  -v,--verbose                    verbose output [false]
#  -wfrs,--writefrsubpaths         write the FR subpaths file at end [false]
#  -wpfr,--writepathfrs            write the path FR file at end [false]
#  -wsf,--writesavefiles           write save files after each FR is found
#                                  [false]

######################################################################################################################
## perfect path matching to FR is alpha=1, kappa=0
## use alpha=0 to represent alpha=epsilon (arbitrarily small positive number requiring at least one FR node on a path)
## use kappa=-1 to represent kappa=infinity (unlimited extra nodes between FR nodes on a path)
######################################################################################################################

## required parameters
graph=$1
alpha=$2
kappa=$3
priorityoption=$4

## use $5-$15 for extra parameters

echo "# $graph alpha=$alpha kappa=$kappa priorityOption=$priorityoption $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15}"

## TXT input
## DO NOT USE -XX:+UseG1GC!!! Causes hang at certain RAM limit.
java -server -Xms10g -Xmx500g -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.fr.FRFinder \
	--verbose --txt --graph=$graph --alpha=$alpha --kappa=$kappa --priorityoption=$priorityoption \
	$5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15}
