#!/bin/sh
# usage: PangenomicGraph
#  -arff,--printarfffile             print out an ARFF file of path node
#                                    participation [false]
#  -dncp,--dropnocallpaths           drop no-call nodes and paths that
#                                    traverse them [false]
#  -ecc,--equalizecasescontrols      reduce cases or controls to make equal
#                                    in number [false]
#  -g,--graph <arg>                  name of graph
#  -l,--labelfile <arg>              tab-delimited file containing one
#                                    sample<tab>label pair per line
#  -list,--listfile <arg>            load graph from a PLINK list file
#                                    (requires labelfile)
#  -maxc,--maxcases <arg>            maxiumum number of cases in the graph
#  -nodepaths,--printnodepathsfile   print out node paths file [false]
#  -nodes,--nodesfile <arg>          load graph nodes from a nodes file
#                                    (<name>.nodes.txt)
#  -paths,--pathsfile <arg>          load paths from a paths file
#                                    (<name>.paths.txt)
#  -pca,--printpcafile               print out path pca file [false]
#  -svm,--printsvmfile               print out a LIBSVM-compatible file of
#                                    path node participation [false]
#  -v,--verbose                      verbose output (false)
#  -vcf,--vcffile <arg>              load graph from a VCF file (requires
#                                    labelfile)


GRAPHPREFIX=$1
PATHSPREFIX=$2

java -server -cp "build/install/pangenomics/lib/*" org.ncgr.pangenomics.genotype.PangenomicGraph -svm -v -g $GRAPHPREFIX -nodes $GRAPHPREFIX -paths $PATHSPREFIX
